language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: eRfTd0lEnWubnHWK3U8Z3xPHT2mjrjVrHTVEu5gAYJZsP5srVk8TXQcuOUoE8pdnMu4hh/h/8iEyPBDW/2nMJ68L7JZXvTY5HGJLOqV1Jrv67MFXC6VUFLO9uv353Cxqlbeb2uoiokw5pPngAFuPx6ZAPYPUtInXEG/N7bDz1PfIQC0nblTX6UThC/Ok8DkLO21789G4sD71hAUfB0queU9yMJ/wQWKnPH5fNg+NhngkI5uaKWDIjFfFNNfKNl57ogdLpobvfELISGPlegQDD9V7IgYEr+IM7zgLXdsqa7VycK46EZfvWOkZumsbqeL20LZcDAt2gw2FiH2rzWKFYHl3KxCrenvF1jaEc0u1ZMMjoQZ3TaglgnuW2xIOjNYI7a6y8N9OyAV1x5gwCpESTBZZ+Itn3dkEWF/DWTa0maSIovcQfTtm87sDPgwHSi/EYsj8XoMfo6o7EeLQ4aPwrDM/W2TVG2qyMb7x3Y3Qvk7vYJaZ3+LgG0Jmji4MOzyHIEP+qJ3V6zzKC7EEEX7mnX5WgX8u/xj2F69TdXKr6MIkSPUr64ZaPHJjMej9T5E9bOuJAqaOon/Nv6r+Mnt+q0upjS+6Y8QoNcAu5KepmG7qg83PGiuSAy5GVeibkGmcjn/ZqzrGO2ur6iKuxM8NU/0qRmMXki7i4pqVb/fwsys=
  app: cse112tester
  on:
    repo: m1wen/cse112test
